version: "3.9"

services:
  postgres:
    container_name: rutas-postgres
    build:
      context: ..
      dockerfile: DockerFolder/Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../db/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \"$${POSTGRES_USER:-postgres}\""]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
